apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: dlink-session
spec:
  image: anjia0532/flink:1.14.5-scala_2.12-java8-5
  flinkVersion: v1_14
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
