apiVersion: v1
kind: Service
metadata:
  name: dlink
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: dlink-flink
  type: ClusterIP