apiVersion: v1
kind: PersistentVolume
metadata:
   name: myhost-doris-fe
   labels:
     app: doris-fe
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: doris-local-storage-fe
   local:
      path: /data0/doris/fe
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - myhost
