apiVersion: v1
kind: PersistentVolume
metadata:
   name: mdlapubu-doris-broker
   labels:
     app: doris-broker
spec:
   capacity:
      storage: 1Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: doris-local-storage-broker
   local:
      path: /data0/doris/broker
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - mdlapubu
