apiVersion: v1
kind: PersistentVolume
metadata:
   name: mdubu-doris-be
   labels:
     app: doris-be
spec:
   capacity:
      storage: 40Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: doris-local-storage-be
   local:
      path: /data0/doris/be
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - mdubu
