apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  #image: "harbor.my.org:1080/bronzels/spark-hadoop-3.2.1-juicefs:3.3.1"
  image: "harbor.my.org:1080/bronzels/spark-juicefs:3.3.1"
  mainClass: org.apache.spark.examples.JavaSparkPi
  mainApplicationFile: "local:///app/hdfs/spark/examples/jars/spark-examples_2.12-3.3.1.jar"
  sparkVersion: "3.3.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.1
    serviceAccount: my-spark
    volumeMounts:
      - name: "app-pi-test-claim"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.1
    volumeMounts:
      - name: "app-pi-test-claim"
        mountPath: "/tmp"