FROM harbor.my.org:1080/bronzels/hive-ubussh-juicefs:0.1 as hadoop

#FROM harbor.my.org:1080/bronzels/spark-juicefs:3.3.1 as final
FROM harbor.my.org:1080/bronzels/spark-juicefs-volcano-rss:3.3.1 as final

USER root
COPY sources.list /etc/apt
RUN apt-get update
RUN apt install -y bc

USER hdfs
WORKDIR /app/hdfs/spark/work-dir

COPY --chown=hdfs:root spark-sql-job.sh /app/hdfs/spark/work-dir/

COPY --from=hadoop --chown=hdfs:root /app/hdfs/hive/hive-testbench/spark-queries-tpcds /app/hdfs/spark/work-dir/spark-queries-tpcds

COPY --chown=hdfs:root podgroups /app/hdfs/spark/work-dir/podgroups

