apiVersion: v1
kind: Service
metadata:
  name: {{ template "sparksrv.fullname" . }}-thrs
  labels:
    app: {{ template "sparksrv.fullname" . }}-thrs
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPortThrift }}
    targetPort: {{ .Values.service.internalPortThrift }}
    protocol: TCP
    name: {{ .Chart.Name }}
  selector:
    app: {{ template "sparksrv.fullname" . }}-thrs
