---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
        [client]
        default-character-set=utf8mb4
        [mysql]
        default-character-set=utf8mb4
        [mysqld] 
        secure_file_priv=/var/lib/mysql
        sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        #default-time-zone = 'Asia/Shanghai'
        default-time_zone = '+8:00'
        interactive_timeout = 1800
        wait_timeout = 1800
        max_connections = 8192
        max_user_connections= 2048
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql-deploy
type: Opaque
data:
  database-dba-password: MTIzNDU2
