apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce   #在rancher/local-path-provisioner里，这里不能用ReadWriteMany
  storageClassName: local-path     #此处为你命名的StorageClass name
  resources:
    requests:
      storage: 4Gi
