kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meta-mysql-claim
  annotations:
    #volume.beta.kubernetes.io/storage-class: "nfs-client"
    volume.beta.kubernetes.io/storage-class: "local-path"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
