apiVersion: v1
kind: ConfigMap
metadata:
  name: init-database
data:
  execute01.sql: |-
    -- create database
    CREATE DATABASE IF NOT EXISTS dataease DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    -- create user and grant authorization
    GRANT ALL ON dataease.* TO 'dataease'@'%' IDENTIFIED BY '${USER_IDENTIFIER}';
    USE dataease;
