apiVersion: v1
kind: PersistentVolume
metadata:
   name: mdlapubu-hdfs-pvdn
   labels:
     app: hdfs
spec:
   capacity:
      storage: 80Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: hdfs-local-storage-dn
   local:
      path: /data0/hdfs/pvdn
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - mdlapubu
