ADD fuse-3.12.0.tar.xz /usr/local/hadoop/
RUN cd fuse-3.12.0/
RUN mkdir build
RUN cd build
RUN apt-get install -y python3 python3-pip ninja-build
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN pip install meson
RUN meson ..
RUN ninja
RUN python3 -m pytest test/
RUN ninja install


