apiVersion: v1
kind: Pod
metadata:
  name: juicefs-test
  labels:
    app: nginx
spec:
  containers:
    - name: juicefs-test
      image: harbor.my.org:1080/chenseanxy/hadoop-ubussh-juicefs:3.2.1-nolib
      imagePullPolicy: Always
      command: ["tail"]
      args: ["-f", "/dev/null"]
      resources:
        requests:
          memory: "16Gi"
          cpu: "4000m"
        limits:
          memory: "16Gi"
          cpu: "4000m"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
