apiVersion: v1
kind: Secret
metadata:
  name: juicefs-sc-secret
type: Opaque
stringData:
  name: miniofspvc
  metaurl: redis://:redis@my-redis-master.redis.svc.cluster.local:6379/2
  storage: minio
  bucket: https://minio.minio-tenant-1.svc.cluster.local/jfspvc?tls-insecure-skip-verify=true
  access-key: 4UFXGHAUY3W02Z2OM247
  secret-key: MCzN5DsK1o8TF5tzQ2TkjQRv39IoLiqc8FaKFEWP
  envs: "{TZ: Asia/Shanghai}"
