apiVersion: v1
kind: Secret
metadata:
  name: juicefs-sc-secret
type: Opaque
stringData:
  name: miniofspvc
  metaurl: redis://:redis@my-redis-master.redis.svc.cluster.local:6379/2
  storage: minio
  bucket: https://minio.minio-tenant-1.svc.cluster.local/jfspvc?tls-insecure-skip-verify=true
  access-key: JCTHLDGEMZM03OF5B163
  secret-key: DrTRA1zlIznEY5vY9rVrt68fjUO0z98ZGPCo39ZX
  envs: "{TZ: Asia/Shanghai}"
