apiVersion: batch/v1
kind: Job
metadata:
  name: doris-add-bes2fe
  labels:
    app: add-bes2fe
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: add-bes2fe
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-bes-ready
          image: harbor.my.org:1080/base/python:3.8-centos7-netutil
          imagePullPolicy: "IfNotPresent"
          command: ["/tmp/preconf/wait-es.sh","be", "3"]
          volumeMounts:
            - name: config-init-volume
              mountPath: /tmp/preconf
        - name: wait-fes-ready
          image: harbor.my.org:1080/base/python:3.8-centos7-netutil
          imagePullPolicy: "IfNotPresent"
          command: ["/tmp/preconf/wait-es.sh","fe", "3"]
          volumeMounts:
            - name: config-init-volume
              mountPath: /tmp/preconf
      containers:
        - name: add-bes2fe
          image: mysql:5.7
          imagePullPolicy: "IfNotPresent"
          #command: ["tail", "-f", "/dev/null"]
          command: ["/tmp/preconf/add-bes.sh", "3"]
          volumeMounts:
            - name: config-init-volume
              mountPath: /tmp/preconf
      volumes:
        - name: config-init-volume
          configMap:
            name: doris-configmap
            defaultMode: 493
