kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: doris-be
  labels:
    app: doris-be
spec:
  replicas: 3
  serviceName: be
  selector:
    matchLabels:
      app: doris-be
  template:
    metadata:
      labels:
        app: doris-be
    spec:
      #nodeName: master-1
      nodeSelector:
        component.doris/be: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: doris-be
          env:
            - name: BE_IPADDRESS
              valueFrom:
                 fieldRef:
                   fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: harbor.my.org:1080/doris/doris-be:1.2.2
          #command: [ "/bin/bash", "-ce", "/opt/apache-doris/be/bin/start_be.sh --daemon;tail -f /dev/null" ]
          command: [ "/bin/bash", "-ce", "/tmp/preconf/bootstrap.sh 3 9050 9030 9010 /opt/apache-doris/be/storage 8000;tail -f /dev/null" ]
          #command: [ "/tmp/preconf/bootstrap.sh", "3", "9050", "9030", "9010", "tail", "-f", "/dev/null" ]
          #args: hosts be_hearbeat_port fe_mysql_port
          #bootstrap.sh will assemble args and call init_be/fe.sh
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8040
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - -c
                  - '/tmp/preconf/shutdown.sh 3 9030 /opt/apache-doris/be/storage > /opt/apache-doris/be/storage/stop.log 2>&1'
          ports:
            - containerPort: 9060
              protocol: TCP
            - containerPort: 9070
              protocol: TCP
            - containerPort: 8040
              protocol: TCP
            - containerPort: 9050
              protocol: TCP
            - containerPort: 8060
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 18G
            requests:
              cpu: 200m
              memory: 1G
          volumeMounts:
            - mountPath: /opt/apache-doris/be/storage
              name: volume-be
            - name: config-init-volume
              mountPath: /tmp/preconf
      volumes:
        - name: config-init-volume
          configMap:
            name: doris-configmap
            defaultMode: 493
  volumeClaimTemplates:
    - metadata:
        name: volume-be
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        storageClassName: "doris-local-storage-be"
        volumeMode: Filesystem
