apiVersion: v1
kind: Service
metadata:
  name: be
  labels:
    app: doris-be
spec:
  sessionAffinity: ClientIP
  selector:
    app: doris-be
  ports:
    - name: heartbeat
      port: 9050
    - name: http
      port: 8040
