apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: doris-fe
spec:
  sessionAffinity: ClientIP
  selector:
    app: doris-fe
  ports:
    - name: mysql
      port: 9030
    - name: http
      port: 8030
