apiVersion: v1
kind: Pod
metadata:
  name: bitsail-client
  labels:
    app: bitsail
spec:
  containers:
    - name: bitsail-client
      image: "harbor.my.org:1080/integrate/bitsail:0.1.0"
      command: ["tail"]
      args: ["-f", "/dev/null"]
