FROM java:8
CMD ["mkdir", "-p", "/root/db_tools"]
WORKDIR /root/db_tools
ADD mysql-connector-java.jar .
ADD database-tools-1.0.jar .
ENTRYPOINT ["java","-cp","./database-tools-1.0.jar:./mysql-connector-java.jar","com.dameng.dmcp.tools.DatabaseTools"]