ingress:
  enabled: true
  host: demo.apps.dataease.com
  annotations: {}
    ## example for ingress annotions.
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"      
  https:
    enabled: false
    secretName: ""

common:
  imagePrefix: "registry.cn-qingdao.aliyuncs.com/dataease/"
  imagePullSecrets: nil
  storageClass: de-nfs
  imagePullPolicy: IfNotPresent
  dataease:
    host: dataease
    logintimeout: 480
    nodeport_port: 30081

redis:
  host: 127.0.0.1
  password: ""
  database: 0

DataEase:
  enabled: true
  engine_mode: simple
  image: dataease
  imageTag: "v1.18.4"
  replicas: 1
  resourceLimits:
    cpu: 4
    memory: 8G
  properties: |-
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.url=jdbc:mysql://${MYSQL_ADDR:127.0.0.1}:3306/dataease?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username=${MYSQL_USERNAME:dataease}
    spring.datasource.password=${MYSQL_PASSWORD:dataease}
    dataease.init_password=${INIT_PASSWORD:dataease123456}
    dataease.login_timeout={{.Values.common.dataease.logintimeout}}
    logger.level=INFO
    engine_mode={{.Values.DataEase.engine_mode}}
    #添加redis连接信息
    spring.cache.type=redis

    #redis公共配置
    spring.redis.timeout=10000
    spring.redis.lettuce.pool.max-active=8
    spring.redis.lettuce.pool.max-wait=-1
    spring.redis.lettuce.pool.max-idle=8
    #单机模式 redis 配置
    spring.redis.database={{.Values.redis.database}}
    spring.redis.host={{.Values.redis.host}}
    spring.redis.port=6379
    spring.redis.password={{.Values.redis.password}}
  java_options: " -Dfile.encoding=utf-8 -Xmx8192m -XX:MaxPermSize=1024m -Xss5m"

logPersistence:
  enabled: true
  accessModes: ReadWriteOnce
  size: 10Gi

dataPersistence:
  accessModes: ReadWriteOnce
  size: 10Gi
