ARG FLINKOP_VERSION=?
#FROM flink-kubernetes-operator:${FLINKOP_VERSION}
FROM harbor.my.org:1080/flink-kubernetes-operator:${FLINKOP_VERSION}
ARG JUICEFS_VERSION=?
ARG STARROCKS_CONNECTOR_VERSION=?
ARG FLINK_SHORT_VERSION=?

RUN mkdir $FLINK_HOME/conf

USER root
COPY --chown=flink:flink core-site.xml $FLINK_HOME/conf/
COPY --chown=flink:flink hdfs-site.xml $FLINK_HOME/conf/
COPY --chown=flink:flink hive-site.xml $FLINK_HOME/conf/
COPY --chown=flink:flink juicefs-hadoop-${JUICEFS_VERSION}-jdk11-debian11.jar $FLINK_HOME/plugins/

COPY --chown=flink:flink starrocks-connector-for-apache-flink-${STARROCKS_CONNECTOR_VERSION}/target/flink-connector-starrocks-${STARROCKS_CONNECTOR_VERSION}_flink-${FLINK_SHORT_VERSION}.jar $FLINK_HOME/plugins/
USER flink
