ARG TARGET_BUILT=?
FROM harbor.my.org:1080/flink/flink-juicefs-${TARGET_BUILT}:1.15.4 as build_1.15
FROM harbor.my.org:1080/flink/flink-juicefs-${TARGET_BUILT}:1.16.1 as build_1.16
FROM harbor.my.org:1080/flink/flink-juicefs-${TARGET_BUILT}:1.17.0 as final

COPY --from=build_1.15 /opt/flink /opt/flink-1.15
COPY --from=build_1.16 /opt/flink /opt/flink-1.16
RUN mv /opt/flink /opt/flink-1.17
ENV FLINK_HOME=
ENV PATH=$OLDPATH
COPY version-env.sh /opt/