---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-job-history-server-deployment
spec:
  selector:
    matchLabels:
      app: flink-job-history-server
  replicas: 1
  template:
    metadata:
      labels:
        app: flink-job-history-server
    spec:
      containers:
        - name: history-server
          #image: harbor.my.org:1080/flink/flink-juicefs-hadoop3hive3:1.15.4
          image: harbor.my.org:1080/flink/flink-juicefs-hadoop3hive3:1.17.0
          command: ["/opt/flink/bin/historyserver.sh","start-foreground"]
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: flink-job-history-server-service
spec:
  selector:
    app: flink-job-history-server
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082