kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: minio-sc
provisioner: minio.min.io
parameters:
  serverEndpoint: "http://my-minio-0.my-minio.minio-operator.svc.cluster.local:9000"
  accessKey: "INE1337BT1CWKY1QFCKB"
  secretKey: "1cVBLXO8MCSBgm9V0JGIDp7BPQmgcx3qUtbBhjMi"
  bucket: "scstorage"
  region: "us-east-1"
