kind: Pod
apiVersion: v1
metadata:
  name: flink-user
spec:
  containers:
  - name: user-pod
    image: harbor.my.org:1080/flink/flink:cdc-3.0.1-flink-1.18.1
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "tail -f /dev/null"
    volumeMounts:
      - name: user-pvc
        mountPath: "/opt/flink/user"
  volumes:
    - name: user-pvc
      persistentVolumeClaim:
        claimName: jfs-flink-user-claim
