kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jfs-flink-log-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "juicefs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jfs-flink-state-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "juicefs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
      
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jfs-flink-user-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "juicefs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi 