FROM registry.cn-hangzhou.aliyuncs.com/rookieops/docker:19.03.11

RUN apk update
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo Asia/Shanghai > /etc/timezone
RUN apk del tzdata

RUN apk add jq
RUN apk add bash
RUN cat /etc/passwd
RUN sed -i "s@root:x:0:0:root:\/root:\/bin\/ash@root:x:0:0:root:\/root:\/bin\/bash@g" /etc/passwd
RUN cat /etc/passwd
RUN apk add git

#RUN wget -c https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.9.2/kustomize_v3.9.2_linux_amd64.tar.gz
COPY kustomize_v3.9.2_linux_amd64.tar.gz $PWD/
RUN tar xzvf kustomize_v3.9.2_linux_amd64.tar.gz
RUN chmod a+x kustomize
RUN mv kustomize /usr/bin

RUN rm -rf /tmp/* /var/cache/apk/*

COPY whodeps-docker-kustomize.sh /opt/
COPY app-docker-kustomize.sh /opt/
