FROM openjdk:8-jdk-alpine

#镜像的制作人
MAINTAINER alexliu/alexliu@acadsoc.com

RUN apk update
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo Asia/Shanghai > /etc/timezone
RUN apk del tzdata
RUN rm -rf /tmp/* /var/cache/apk/*
