FROM python:3-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo Asia/Shanghai > /etc/timezone
RUN apk del tzdata

RUN mkdir /root/.pip
COPY pip.conf /root/.pip/pip.conf
RUN ls /root/.pip/
RUN cat /root/.pip/pip.conf
RUN pip config list

RUN apk add postgresql-dev musl libffi-dev musl-dev gcc g++

RUN apk add freetds-dev
ENV PYMSSQL_BUILD_WITH_BUNDLED_FREETDS 1
RUN echo $PYMSSQL_BUILD_WITH_BUNDLED_FREETDS
RUN pip install psycopg2==2.8.6 pymssql==2.1.5 PyMySQL==1.0.2
RUN pip install pandas==1.2.1 numpy==1.19.5
RUN pip install cffi==1.14.4 Flask-Admin==1.5.7 MarkupSafe==1.1.1 pycryptodome==3.10.1 SQLAlchemy==1.3.3

RUN rm -rf /tmp/* /var/cache/apk/*

EXPOSE 5000

CMD ["/start.sh"]


