FROM registry.cn-hangzhou.aliyuncs.com/rookieops/maven:3.5.0-alpine

RUN apk update
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo Asia/Shanghai > /etc/timezone
RUN apk del tzdata
RUN rm -rf /tmp/* /var/cache/apk/*
