FROM harbor.my.org:1080/base/python:3.8-centos7-netutil

RUN yum install -y epel-release centos-release-scl scl-utils

RUN yum install -y devtoolset-7
RUN scl enable devtoolset-7 bash
RUN echo "source scl_source enable devtoolset-7" >> /root/.bashrc

RUN yum install -y devtoolset-10
RUN scl enable devtoolset-10 bash
RUN echo "source scl_source enable devtoolset-10" >> /root/.bashrc

RUN yum install -y automake autoconf libtool

#RUN yum install -y gcc make
#RUN yum install -y gcc-c++ gcc-gfortran
RUN yum install -y kernel-devel tar wget

RUN gcc --version
ENV PATH /opt/rh/devtoolset-7/root/usr/bin:$PATH
RUN make --version
RUN make --version

RUN yum install -y zip unzip

WORKDIR /root/workspace

RUN yum install -y openssl openssh-server openssh-clients
RUN yum install -y ansible sshpass

ENV file=/etc/ssh/sshd_config
RUN cp ${file} ${file}.bk
RUN sed -i 's@#PermitRootLogin prohibit-password@PermitRootLogin yes@g' ${file}
RUN sed -i 's@#PubkeyAuthentication yes@PubkeyAuthentication yes@g' ${file}
RUN sed -i 's@PasswordAuthentication no@PasswordAuthentication yes@g' ${file}

COPY ssh_config /etc/ssh/ssh_config

COPY systemctl /usr/bin/systemctl
RUN chmod a+x /usr/bin/systemctl
RUN systemctl enable sshd.service

RUN echo "root:1234" | chpasswd

RUN ssh-keygen -A

