FROM python:3.7-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo Asia/Shanghai > /etc/timezone
RUN apk del tzdata
RUN rm -rf /tmp/* /var/cache/apk/*

RUN mkdir /root/.pip
COPY pip.conf /root/.pip/pip.conf
RUN ls /root/.pip/
RUN cat /root/.pip/pip.conf
RUN pip config list

