FROM harbor.my.org:1080/base/python:3.8-centos7-netutil-ccplus7-go

RUN yum install -y libaio-devel

WORKDIR /
COPY iotest/mpich-3.2.tar.gz /mpich-3.2.tar.gz
RUN tar -xzvf mpich-3.2.tar.gz
WORKDIR /mpich-3.2
RUN ./configure
RUN make
RUN make install
RUN mpicc || :
ENV MPI_CC=mpicc
