FROM dokken/ubuntu-20.04
USER root
SHELL ["/bin/bash", "-c"]

#设置时间同步和时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY timesyncd.conf /etc/systemd/timesyncd.conf

COPY sources-20.04.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y net-tools inetutils-ping telnet

