FROM ubuntu:22.04

COPY sources-22.04.list /etc/apt/sources.list
RUN apt-get update; exit 0
#RUN apt-get upgrade -y; exit 0

# 添加中文支持
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y locales
RUN locale-gen zh_CN.UTF-8 && \
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
RUN locale-gen zh_CN.UTF-8
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
ENV LC_ALL zh_CN.UTF-8
ENV LC_ALL="C.UTF-8" LANG="C.UTF-8"

# 安装openjdk
RUN set -eux; \
    apt-get install -y openjdk-8-jdk; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    rm -rf /var/cache/oracle-jdk8-installer

RUN apt-get install -y ca-certificates-java; \
    apt-get clean; \
    update-ca-certificates -f; \
    rm -rf /var/lib/apt/lists/*; \
    rm -rf /var/cache/oracle-jdk8-installer

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

RUN export JAVA_HOME

RUN java -version

RUN apt-get update
RUN apt install software-properties-common apt-transport-https curl -y