FROM python:3.7-alpine

RUN apk update
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo Asia/Shanghai > /etc/timezone
RUN apk del tzdata

RUN mkdir /root/.pip
ADD pip.conf /root/.pip
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk add --no-cache gcc python3-dev musl-dev libffi-dev openssl-dev libressl-dev
RUN pip install --no-cache-dir --upgrade pip
RUN pip install cryptography==3.3.1
RUN pip install twine

RUN apk update \
    && apk add --upgrade --no-cache \
        libffi-dev \
        ca-certificates openssl \
                g++ make \
        build-base libpng-dev freetype-dev libexecinfo-dev openblas-dev libgomp lapack-dev \
                libgcc libquadmath musl  \
                libgfortran \
                lapack-dev \
		freetds-dev \
		libxslt-dev libressl-dev \
		postgresql-dev

RUN mkdir /root/.cargo
ADD config /root/.cargo/

RUN pip install pandas==1.2.1
RUN pip install numpy==1.19.5
RUN pip install scipy==1.6.0
RUN pip install scikit-learn==0.24.1

RUN pip install alembic==1.5.4 Flask-Script==2.0.6 gevent==21.1.2 Mako==1.1.4 MarkupSafe==1.1.1 pymssql==2.1.5 SQLAlchemy==1.3.23 zope.interface==5.2.0

RUN pip install pycryptodome==3.10.1

RUN pip install xlrd==2.0.1 prometheus_client==0.9.0
RUN pip install scikit-learn==0.24.1 beautifulsoup4==4.9.3
RUN pip install plotly==5.1.0

RUN pip install python-dateutil==2.8.1 pytz==2020.5 redis==3.5.3 requests==2.25.1 six==1.15.0 urllib3==1.26.3 websocket-client==0.57.0 certifi==2020.12.5 cffi==1.14.4 chardet==4.0.0 Flask==1.1.2 Flask-Migrate==2.6.0 Flask-SQLAlchemy==2.4.4 greenlet==1.0.0 idna==2.10

RUN apk add jq

RUN rm -rf /tmp/* /var/cache/apk/*